### ISSUE TITLE
Multiple hard refreshes - required to view sections , certificate warning also.

### ISSUE THREAD

**Issue by javapapo** [kubernetes/kube-ui#30]
Hello here is my setup
1. Host OS: MacoSX 10.10.5
2. Browser : Firefox 40.0.3
3. Kubernetes: version 1.1.0 Alpha  (but I had the same problem even worse to be honest with 1.0.2/1.0.3 etc)
4. Kubernetes setup: Local host deployment (master- node) using the ' vagrant way, through /cluster/kube-up.sh
5. Vagrant Version: 1.7.4
6. Virtualbox Version : 4.3.30 (Plugins installed).

After the end of the kube-up setup, I have a kubernetes cluster (master and 1 node). 

When I try the link to access the Kube-UI, the first time the page only 'renders' the header. 

Screenshot1 -> [http://postimg.org/image/ycwvd3kb5/]

Then after a hard refresh meaning Command + Shift + R , I get the rest of the page displayed + I get the warning about the browser security/certificate exception (adding it to the known /safe list).

Screenshot2 -> http://postimg.org/image/89tc1i1q7/
ScreenShot3 -> http://postimg.org/image/d1e3cihml/

When eventually I managed to get the full page then , when I try to access other pages from the menu on the right side of the page, I get no response back, trying to do hard refresh a couple of times, it usually fetches and renders a page.

At the same time, when I try to access Heapster, I get a page with a link 'Temporary Redirect' , I click on the page and I am redirected to -> https://10.245.1.2/validate/ , not sure if this a problem though since this is an alpha version.

Thanks for your time.

**Comment by MichielDeMey** [comment]
I have the exact same issue.

Host OS: OSX 10.11
Browser: Chrome 45
Kubernetes version: 1.0.5
Kubernetes setup: Vagrant
Vagrant Version: 1.7.4
Virtualbox Version : 4.3.30

Some observations I've made:

Try to refresh one of the dashboard's files.
e.g. https://10.245.1.2/api/v1/proxy/namespaces/kube-system/services/kube-ui/assets/js/base.js

Every time I refresh a different chunk size is served to my browser. The script is actually not fully transferred and seems to be transferred only partly. The browser still indicates that it's loading the file.

After a couple of hard refreshes I was able to get the whole file instead of only a chunk.

Really weird.

**Comment by hbokh** [comment]
+1
Same issue as I type this, with the almost the same setup as Michiel De Mey, except for OSX --> 10.10.5.
Also no page in FF 40.0.3 at first.

However,  pressing CMD + R multiple times gives the blueish page eventually, where I can explore, view pods, etc.
